use google-double conversion
0ph1uch1/pycjson pull request #10
Opened 2024-04-22 15:37 UTC by Nambers

TODO
- [] free in some points
- [] validate string in decoding
- [] ensure to throw overflow exception when double is invalid? align to std python behavior

2024-04-22 22:27 UTC, Antares0982 requested changes

2024-04-22 22:27 UTC, Antares0982 commented on buildScripts/amalgamation/amalgamation.py
> +import json
remove these files

2024-04-22 22:27 UTC, Antares0982 commented on deps/.gitignore
> +double-conversion/**
remove this file

2024-04-22 22:27 UTC, Antares0982 commented on src/pycJSON_decode.c
> +        if (dconv_s2d_ptr == NULL) {
init in PyInit_cjson

2024-04-23 03:47 UTC, Nambers commented on src/pycJSON_decode.c
> +        if (dconv_s2d_ptr == NULL) {
驳回!

2024-04-23 04:51 UTC, Antares0982 requested changes

2024-04-23 04:51 UTC, Antares0982 commented on src/dconv_wrapper.cpp
> +        static auto d2s = DoubleToStringConverter(DoubleToStringConverter::NO_FLAGS, "Infinity", "NaN", 'e', -324, 308, 0, 0);
static DoubleToStringConverter d2s(DoubleToStringConverter::NO_FLAGS, "Infinity", "NaN", 'e', -324, 308, 0, 0);
```suggestion
        static DoubleToStringConverter d2s(DoubleToStringConverter::NO_FLAGS, "Infinity", "NaN", 'e', -324, 308, 0, 0);
```
This fixes compile error

2024-04-23 04:51 UTC, Antares0982 commented on src/dconv_wrapper.cpp
> +        static auto s2d = StringToDoubleConverter(StringToDoubleConverter::NO_FLAGS, 0.0, Py_NAN, "Infinity", "NaN");
```suggestion
        static StringToDoubleConverter s2d(StringToDoubleConverter::NO_FLAGS, 0.0, Py_NAN, "Infinity", "NaN");
```

2024-04-23 05:11 UTC, merged